### PR TITLE
feat: Create 404 page.

### PR DESCRIPTION
**Pull request by OctoPie559**
I don't know if the page I created matches your needs, but there it is. I hope it does. According to next.js having a not-found.tsx file handles every single missing page.

### CODE REVIEW

**Comment by Elgius** [comment]
Thanks, was aware about the not-found.tsx file handling missing pages but needed someone to make it asap since was busy with backend 😂😂😂. Thanks though, am gonna check your pr now

**Comment by Elgius** [comment]
Merged. Next time run "npm lint" before you send a pull request please since we run lint and your code only failed the lint check

**Comment by OctoPie559** [comment]
Okay no worries at all 😂.

**Comment by OctoPie559** [comment]
Ooh i didn't know that. Next time i will.

**Pull request merged**
